#!/bin/bash -e
cargo fmt -- --check
cargo check --all --examples --tests
cargo check --all --examples --tests --no-default-features --features std-future
cargo check --all --examples --tests --all-features
